x-defaults: &defaults
  user: ${UID}:${GID}

x-env-defaults: &env-defaults
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}
  POSTGRES_HOST: ${POSTGRES_HOST:-${POSTGRES_CONTAINER_NAME:-geonature-atlas-postgres}}

services:

  atlas:
    <<: *defaults
    build:
      context: ./build/atlas/
      args:
        - ATLAS_IMAGE=${ATLAS_IMAGE:-ghcr.io/pnx-si/geonature-atlas:1.7.1}
        - UID=${UID}
        - GID=${GID}
        - HOST_USER=${HOST_USER}
    image: ${ATLAS_IMAGE:-ghcr.io/pnx-si/geonature-atlas:1.7.1}
    container_name: ${ATLAS_CONTAINER_NAME:-geonature-atlas}
    environment:
      <<: *env-defaults
      ATLAS_ALTITUDES: ${ATLAS_ALTITUDES:-"(0 500 1000 1500 2000 2500 3000 3500 4000)"}
      ATLAS_TYPE_TERRITOIRE: ${ATLAS_TYPE_TERRITOIRE:-"PEC"}
      ATLAS_TYPE_MAILLE: ${ATLAS_TYPE_MAILLE:-"M1"}
      ATLAS_TAXHUB_DISPLAYED_ATTRIBUTES: ${ATLAS_TAXHUB_DISPLAYED_ATTRIBUTES}
      ATLAS_MOST_OBSERVED_TIME: ${ATLAS_MOST_OBSERVED_TIME:-"15"}
      ATLAS_INSTALL_SCHEMA: ${ATLAS_INSTALL_SCHEMA:-false}
      ATLAS_RESET_SCHEMA: ${ATLAS_RESET_SCHEMA:-false}
      # WARNING: don't set default value for ATLAS_URL_APPLICATION, it must be set in .env file
      ATLAS_URL_APPLICATION: ${ATLAS_URL_APPLICATION}
      ATLAS_APPLICATION_ROOT: ${ATLAS_PREFIX}
      ATLAS_TAXHUB_URL: ${ATLAS_TAXHUB_URL:-taxhub.${HOST}/}
      ATLAS_REMOTE_MEDIAS_URL: ${ATLAS_REMOTE_MEDIAS_URL:-taxhub.${HOST}/}
      ATLAS_REDIMENSIONNEMENT_IMAGE: ${ATLAS_REDIMENSIONNEMENT_IMAGE:-true}
      ATLAS_SECRET_KEY: ${ATLAS_SECRET_KEY}
      ATLAS_SQLALCHEMY_DATABASE_URI: ${ATLAS_SQLALCHEMY_DATABASE_URI:-"postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"}
      ATLAS_TEMPLATES_AUTO_RELOAD: "true"
    volumes:
      - ${CONFIG_ATLAS_DIRECTORY}:/dist/config
      - ${CUSTOM_ATLAS_DIRECTORY}:/dist/static/custom
      - ${ASSETS_DIRECTORY}/atlas:/assets
    network_mode: "host"
    healthcheck:
      test: ["CMD-SHELL", "/assets/healthcheck.sh"]
      interval: ${ATLAS_HEALTHCHECK_INTERVAL}
      timeout: 10s
      retries: 20
      start_period: 0s
    logging:
      options:
        tag: ${ATLAS_CONTAINER_NAME:-geonature-atlas}
